### PR TITLE
add option to disable code signing and set code sign identity w/ empty value

### PR DESCRIPTION
**Pull request by j3ffrw**
add option to disable code signing and set code sign identity w/ empty value

### CODE REVIEW

**Comment by partymola** [comment]
This looks super duper useful. Can this please be approved for merge?

**Comment by staticfunction** [comment]
awesome! I want this!

**Comment by alexanderlink** [comment]
Hi, thanks for your contribution. Your change looks good to me, but I have to discuss the impact on our production environment with my colleagues. The only impact for us is codeSignIdentity could be empty now, but I don't think this is an issue.

@marcusholl @IKirilova see e.g. here for more information about `Developing application without iOS Developer program membership`: http://iphonedevwiki.net/index.php/Xcode

**Comment by sreedhargs89** [comment]
We have merged the pull request with #156

**Pull request closed without merging**
